#pragma once
#include "../MSP/MSP.h"
#include <ArduinoJson.h>

#define NAME_LENGTH 3
#define NODES_MAX 6

// Defines an internal representation of a peer
struct peer_t {
   uint8_t id;
   uint8_t host;
   uint8_t state;
   uint8_t lost;
   uint8_t broadcast;
   uint32_t updated;
   uint32_t lq_updated;
   uint8_t lq_tick;
   uint8_t lq;
   int rssi;
   float distance;
   int16_t direction;
   int16_t relalt;
   msp_raw_gps_t gps;
   msp_raw_gps_t gps_pre;
   uint32_t gps_pre_updated;
   msp_analog_t fcanalog;
   char name[NAME_LENGTH + 1];
   uint32_t packetsReceived;
};

class PeerManager
{
public:
    const peer_t *getPeer(uint8_t index);
    peer_t *getPeerMutable(uint8_t index);
    // Looks up a peer by its stable LoRa slot id (1..NODES_MAX), not table index.
    // Returns nullptr if id is out of range. Spoofing-aware, like getPeer().
    const peer_t *getPeerById(uint8_t id);
    void reset();
    uint8_t count(bool active = false);
    uint8_t count_active();
    void statusJson(JsonDocument *doc);
    void loop();
    static PeerManager *getSingleton();

    void enableSpoofing(bool enabled);
    // Overrides a single spoofed peer's position/course for repeatable bench testing,
    // instead of the fixed 100m-ring generated by getSpoofedPeer().
    void spoofPeer(uint8_t index, double lat, double lon, double course, double speed = 0);
    // Sends peer `index` around a closed regular-hexagon patrol path centered on
    // (centerLat, centerLon), `sideLength` meters per edge, at constant `speed` (m/s).
    // Gives it a heading that changes at each vertex instead of standing still or
    // moving in lockstep with our own position, so FollowManager has a moving,
    // independent target to chase for bench testing. Also enables spoofing.
    // Altitude starts at our own current altitude (GNSSManager::getLocation()) + 10m,
    // climbs linearly to a fixed 100m at the halfway point of the loop (the vertex
    // between the 3rd and 4th edge), then descends linearly back to the start altitude
    // by the time the loop closes.
    void spoofPeerHexPath(uint8_t index, double centerLat, double centerLon, double sideLength, double speed);

private:
    static constexpr uint8_t HEX_PATH_SIDES = 6;
    static constexpr double HEX_PATH_PEAK_ALT_M = 100.0;

    // Tracks a peer patrolling a closed regular-hexagon path, advanced each PeerManager::loop().
    struct spoofHexPath_t {
        bool active = false;
        double centerLat = 0;
        double centerLon = 0;
        double sideLength = 0; // meters per edge
        double speed = 0;      // m/s
        double startAlt = 0;   // meters; altitude at the loop's start/end vertex
        uint8_t legIndex = 0;  // 0..HEX_PATH_SIDES-1, edge currently being flown
        double legProgress = 0; // meters traveled into the current edge
        uint32_t lastUpdate = 0;
    };

    peer_t peers[NODES_MAX];
    peer_t spoofedPeers[NODES_MAX];
    // Whether spoofedPeers[index] was set explicitly via spoofPeer()/spoofPeerHexPath() and
    // should not be overwritten by getSpoofedPeer()'s automatic ring generation.
    bool spoofOverride[NODES_MAX] = {false};
    spoofHexPath_t spoofHexPaths[NODES_MAX];
    peer_t *getSpoofedPeer(uint8_t index);
    // Advances spoofHexPaths[index] by elapsed time and writes the result into spoofedPeers[index].
    void updateHexPathPeer(uint8_t index);

    // When true, MSPManager will inject fake peers
    bool spoofingPeers = false;
};

// The locked peer is stale if it hasn't updated within timeout_ms, or is flagged lost.
// Deliberately takes the timeout as a parameter rather than a hardcoded constant so this
// helper has no dependency on the follow module's configuration. Kept inline (rather than
// in PeerManager.cpp) so it links into the native Follow test env without pulling in the
// rest of PeerManager.cpp's hardware-only dependencies.
inline bool peer_is_stale(const peer_t *peer, uint32_t timeout_ms)
{
    if (peer == nullptr || peer->id == 0)
    {
        return true;
    }

    if (peer->lost)
    {
        return true;
    }

    return (millis() - peer->updated) > timeout_ms;
}